# -*- coding: utf-8 -*-
"""Test Bias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyJb0RJ-KTyuTjZAWpAkeI1SV6M9YxmS

# Importing Libraries and Data Set
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor  # or RandomForestClassifier for categorical ratings
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MultiLabelBinarizer

"""# **Load the datasets**



"""

ingredient = pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/Data/ingr_map.pkl")
recipes = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data/PP_recipes.csv")
names = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Data/RAW_recipes.csv")
ratings = pd.read_csv("/content/drive/MyDrive/RAW_interactions.csv")  # Assuming you have this
ingr_map = pd.read_pickle("/content/drive/MyDrive/Colab Notebooks/Data/ingr_map.pkl")

"""# **Convert IDs to Names**"""

# Function to flatten the list of lists
def flatten_list_of_lists(list_of_lists):
    return [item for sublist in list_of_lists for item in sublist]

# Flatten the ingredient tokens for each recipe
recipes['flattened_ingredient_tokens'] = recipes['ingredient_tokens'].apply(flatten_list_of_lists)

# Assuming ingr_map is a DataFrame with an 'id' column that maps to 'replaced' or another column with ingredient names
# Create a dictionary for id to ingredient name mapping
id_to_ingredient = pd.Series(ingr_map['replaced'].values, index=ingr_map['id']).to_dict()

# Function to convert IDs to ingredient names
def ids_to_names(ids):
    return [id_to_ingredient.get(id, "Unknown") for id in ids]

# Map IDs to names
recipes['ingredient_names'] = recipes['flattened_ingredient_tokens'].apply(ids_to_names)

# Example of how to encode these names if needed for a model
mlb = MultiLabelBinarizer()
ingredients_encoded = mlb.fit_transform(recipes['ingredient_names'])
ingredients_df = pd.DataFrame(ingredients_encoded, columns=mlb.classes_)

# Now ingredients_df can be used as part of your feature set for machine learning

"""# **Combine Features**"""

# Combine the encoded ingredients with other features from the recipes DataFrame
full_features = pd.concat([recipes.drop(['ingredient_tokens', 'flattened_ingredient_tokens', 'ingredient_names'], axis=1), ingredients_df], axis=1)

"""# **Data Exploration and Visualization**

"""

# Plotting the distribution of calorie levels
sns.histplot(data=recipes, x='calorie_level', bins=30)
plt.title('Distribution of Calorie Levels')
plt.show()

"""# **Potential Analysis: Ingredient Diversity**"""

recipes['ingredient_count'] = recipes['ingredient_ids'].apply(lambda x: len(x.split(',')))

# Now, plot the distribution of ingredient counts
sns.histplot(data=recipes, x='ingredient_count', bins=30)
plt.title('Distribution of Ingredient Counts per Recipe')
plt.show()

"""# **Prepare the Data**

<table>
  <tr>
    <td>*   American</td>
    <td>*   Cajun/Creole (Louisiana, USA)</td>
  </tr>
  <tr>
    <td>*   Australian</td>
    <td>*   Caribbean</td>
  </tr>
  <tr>
    <td>*   Chinese</td>
    <td>*   Cuban</td>
  </tr>
  <tr>
    <td>*   Ethiopian</td>
    <td>*   Filipino</td>
  </tr>
  <tr>
    <td>*   French</td>
    <td>*   German</td>
  </tr>
  <tr>
    <td>*   Greek</td>
    <td>*   Indian</td>
  </tr>
  <tr>
    <td>*   Indonesian</td>
    <td>*   Italian</td>
  </tr>
  <tr>
    <td>*   Japanese</td>
    <td>*   Korean</td>
  </tr>
  <tr>
    <td>*   Lebanese</td>
    <td>*   Malaysian</td>
  </tr>
  <tr>
    <td>*   Mediterranean</td>
    <td>*   Mexican</td>
  </tr>
  <tr>
    <td>*   Moroccan</td>
    <td>*   Peruvian</td>
  </tr>
  <tr>
    <td>*   Russian</td>
    <td>*   Scandinavian</td>
  </tr>
  <tr>
    <td>*   South African</td>
    <td>*   Spanish</td>
  </tr>
  <tr>
    <td>*   Thai</td>
    <td>*   Turkish</td>
  </tr>
  <tr>
    <td>*   Vietnamese</td>
    <td></td>
  </tr>
</table>
"""

cuisine_keywords = {
    'Italian': [ 'italian', 'pasta', 'pizza', 'risotto', 'tiramisu', 'gelato', 'panettone', 'espresso', 'cappuccino', 'lasagna', 'spaghetti', 'ravioli', 'gnocchi', 'fettuccine', 'tagliatelle', 'carbonara', 'bolognese', 'alfredo', 'pesto', 'arrabbiata', 'marinara', 'amatriciana', 'cipollata', 'aglio e olio', 'puttanesca', 'saltimbocca', 'osso buco', 'cannoli', 'panna cotta', 'affogato', 'bruschetta', 'focaccia', 'ciabatta', 'arancini', 'calzone', 'minestrone', 'zuppa toscana', 'ribollita', 'caponata', 'vitello tonnato', 'prosciutto', 'mortadella', 'soppressata', 'parmigiano reggiano', 'mozzarella', 'ricotta', 'gorgonzola', 'pecorino', 'grana padano', 'asiago', 'taleggio', 'fontina', 'mascarpone', 'burrata', 'bresaola', 'pancetta', 'coppa', 'capicola', 'porchetta', 'polenta', 'cioppino', 'stracciatella', 'aceto balsamico', 'truffle oil', 'limoncello', 'aperitivo', 'digestivo', 'cannelloni', 'tortellini', 'crostini', 'cacciatore', 'involtini', 'marsala', 'piccata', 'scaloppine', 'gelato', 'sorbetto', 'zeppole', 'sfogliatella', 'pizzelle', 'stuffed peppers', 'antipasto', 'caprese', 'insalata', 'frittata', 'tartufo', 'gnudi', 'supplì', 'sarde in saor', 'baccalà', 'frutti di mare', 'mare e monti', 'orata', 'branzino', 'cioppino', 'spiedini', 'panforte', 'torrone', 'amaretto', 'sambuca', 'chianti', 'prosecco', 'grappa', 'valpolicella', 'montepulciano', 'barolo', 'amarone', 'limoncello', 'negroni', 'spritz', 'cicchetti', 'polpette', 'ossobuco', 'pasta e fagioli', 'fagioli', 'miele', 'salumi', 'peperoncino', 'aceto', 'finocchio', 'rucola' ],
    'Mexican': [ 'mexican', 'taco', 'enchilada', 'burrito', 'tamale', 'quesadilla', 'fajita', 'chimichanga', 'salsa', 'guacamole', 'chile relleno', 'nachos', 'tortilla', 'mole', 'pozole', 'menudo', 'carnitas', 'carne asada', 'barbacoa', 'al pastor', 'chorizo', 'ceviche', 'flauta', 'sopes', 'tostada', 'chilaquiles', 'torta', 'pambazo', 'aguachile', 'molcajete', 'arroz con pollo', 'picadillo', 'rajas', 'frijoles', 'jalapeno', 'habanero', 'serrano', 'chipotle', 'ancho', 'guajillo', 'poblano', 'cotija cheese', 'queso fresco', 'queso oaxaca', 'queso panela', 'crema', 'aguacate', 'cilantro', 'lima', 'limon', 'maiz', 'nopal', 'tamarindo', 'tequila', 'mezcal', 'pulque', 'horchata', 'agua de jamaica', 'champurrado', 'margarita', 'sangrita', 'pan de muerto', 'churros', 'flan', 'tres leches cake', 'buñuelos', 'cocada', 'mariachi', 'piñata', 'dia de los muertos', 'cinco de mayo', 'chipotle mayo', 'adobo', 'mexican vanilla', 'mexican chocolate', 'mexican oregano', 'epazote', 'achiote', 'tortas ahogadas', 'huarache', 'empanadas', 'totopos', 'salsas', 'charro beans', 'esquites', 'elote', 'tlayuda', 'salbutes', 'panuchos', 'birria', 'michelada', 'clamato', 'chiles en nogada', 'pico de gallo', 'molotes', 'pipian', 'manchamanteles', 'zacahuil', 'cabrito', 'capirotada', 'chalupa', 'gordita', 'entomatada', 'memela', 'caldo tlalpeño', 'escamoles', 'huitlacoche', 'jalisco', 'veracruzana', 'puebla', 'sonora', 'oaxaca', 'yucatan', 'sinaloa' ],
    'Chinese': [ 'chinese', 'dim sum', 'szechuan', 'cantonese', 'mandarin', 'hunan', 'peking duck', 'chow mein', 'kung pao chicken', 'mapo tofu', 'hot pot', 'dumpling', 'spring roll', 'egg roll', 'wonton', 'baozi', 'xiaolongbao', 'jiaozi', 'congee', 'zongzi', 'mooncake', 'biang biang noodles', 'dan dan noodles', 'char siu', 'siu mai', 'har gow', 'lo mein', 'fried rice', 'sweet and sour pork', 'general tso’s chicken', 'sesame chicken', 'beef and broccoli', 'moo shu pork', 'egg foo young', 'lazi ji', 'yu xiang rou si', 'zhajiangmian', 'tangyuan', 'jianbing', 'stinky tofu', 'chinese broccoli', 'chinese cabbage', 'bok choy', 'chive', 'ginger', 'garlic', 'soy sauce', 'hoisin sauce', 'oyster sauce', 'black bean sauce', 'chili sauce', 'duck sauce', 'plum sauce', 'five-spice powder', 'star anise', 'szechuan peppercorn', 'fermented black beans', 'tofu', 'rice wine', 'sesame oil', 'tea egg', 'century egg', 'salted duck egg', 'rice noodles', 'glass noodles', 'bean sprouts', 'snow peas', 'water chestnuts', 'bamboo shoots', 'shiitake mushrooms', 'wood ear mushrooms', 'lotus root', 'red bean paste', 'lychee', 'longan', 'dragon fruit', 'white radish', 'daikon', 'black vinegar', 'rice vinegar', 'sesame paste', 'doufu', 'suan cai', 'luo han guo', 'gai lan', 'xiao long bao', 'la rou', 'ru rou', 'tian bu la', 'zhaliang', 'youtiao', 'fan tuan', 'luo bo gao', 'shao bing', 'haw flakes', 'preserved egg', 'chinese pancake', 'silk tofu', 'dried shrimp', 'pickled vegetables', 'szechuan chili oil', 'chinese mustard', 'chinese parsley', 'winter melon', 'chrysanthemum tea', 'goji berries', 'white pepper', 'black sesame', 'green onion', 'scallion', 'chinese cleaver', 'wok', 'steamer', 'clay pot' ],
    'French': [ 'french', 'baguette', 'croissant', 'bouillabaisse', 'ratatouille', 'quiche', 'tarte tatin', 'souffle', 'crepe', 'mousse', 'foie gras', 'escargot', 'coq au vin', 'boeuf bourguignon', 'cassoulet', 'madeleine', 'clafoutis', 'éclair', 'profiterole', 'macaron', 'opera cake', 'pain au chocolat', 'tarte flambée', 'flamiche', 'blanquette de veau', 'rillettes', 'pâté', 'vichyssoise', 'galette', 'brioche', 'charlotte', 'daube', 'financier', 'flaugnarde', 'fondue', 'gratin dauphinois', 'ratatouille', 'salade niçoise', 'tartiflette', 'navarin', 'poulet basquaise', 'quenelle', 'raclette', 'savarin', 'tarte normande', 'vol-au-vent', 'mille-feuille', 'chouquette', 'croquembouche', 'far breton', 'frangipane', 'kouign amann', 'langres', 'mont d’or', 'reblochon', 'roquefort', 'boursin', 'camembert', 'chèvre', 'comté', 'crottin de chavignol', 'pont l’évêque', 'saint-marcellin', 'tome de savoie', 'andouillette', 'boudin blanc', 'boudin noir', 'chateaubriand', 'confit de canard', 'cordon bleu', 'entrecote', 'filet mignon', 'gougère', 'jambon-beurre', 'niçoise', 'oeufs en meurette', 'pissaladière', 'pot au feu', 'soupe à l’oignon', 'steak tartare', 'tarte de blettes', 'truffade', 'pain perdu', 'sauce béarnaise', 'sauce hollandaise', 'sauce mornay', 'tarte aux pruneaux', 'pain de campagne', 'bouillabaisse', 'fromage' ],
    'Japanese': [ 'japanese', 'sushi', 'ramen', 'teriyaki', 'tempura', 'miso', 'sashimi', 'udon', 'wasabi', 'kaiseki', 'yakitori', 'tonkatsu', 'bento', 'takoyaki', 'okonomiyaki', 'shabu-shabu', 'sukiyaki', 'gyoza', 'edamame', 'katsu', 'donburi', 'onigiri', 'mochi', 'matcha', 'unagi', 'karaage', 'nabe', 'yakiniku', 'fugu', 'chawanmushi', 'soba', 'tamagoyaki', 'izakaya', 'norimaki', 'hiyayakko', 'sencha', 'genmaicha', 'anko', 'daifuku', 'dorayaki', 'wagashi', 'panko', 'furikake', 'miso soup', 'natto', 'tsukemono', 'kombu', 'mirin', 'sake', 'shochu', 'umeshu', 'yuzu', 'ponzu', 'kakigori', 'dashi', 'tamari', 'shoyu', 'wasabi', 'shiitake', 'enoki', 'maitake', 'tsukune', 'nasu', 'daikon', 'shiso', 'renkon', 'kabocha', 'kinpira', 'korokke', 'omurice', 'oshizushi', 'chirashi', 'hanami dango', 'gyudon', 'nikujaga', 'takikomi gohan', 'okowa', 'ochazuke', 'hakusai', 'arare', 'hojicha', 'kamaboko', 'umeboshi', 'teriyaki sauce', 'katsuobushi', 'aji', 'kaki', 'ayu', 'basashi', 'gyokuro', 'kaiseki ryori', 'shiratama', 'taiyaki', 'zaru soba', 'yakizakana', 'yosenabe', 'japchae', 'teppanyaki', 'tendon', 'tenzaru', 'tofu', 'agedashi tofu', 'inari', 'ikura', 'gari', 'maguro', 'toro', 'hamachi', 'tamago' ],
    'Indian': [ 'indian', 'curry', 'masala', 'tandoori', 'biryani', 'chutney', 'dosa', 'naan', 'paneer', 'raita', 'samosa', 'vindaloo', 'roti', 'dal', 'korma', 'pulao', 'chana', 'rajma', 'jalfrezi', 'paratha', 'gulab jamun', 'lassi', 'bhatura', 'chapati', 'pakora', 'papadum', 'jalebi', 'halwa', 'kebab', 'thali', 'uttapam', 'idli', 'vada', 'sambhar', 'bhaji', 'rogan josh', 'kheer', 'puri', 'kulfi', 'tikka masala', 'saag', 'aloo gobi', 'makhani', 'bhindi masala', 'kadhi', 'momo', 'panipuri', 'chaat', 'bhajia', 'bhel puri', 'sev puri', 'kathi roll', 'mutter paneer', 'palak paneer', 'chole bhature', 'gajar ka halwa', 'shawarma', 'fish curry', 'lamb curry', 'chicken curry', 'goat curry', 'beef curry', 'prawn curry', 'malai kofta', 'dal makhani', 'achar', 'basmati rice', 'jeera rice', 'kokum', 'amchur', 'asarfoetida', 'fenugreek', 'garam masala', 'turmeric', 'cardamom', 'cloves', 'cumin', 'coriander', 'mustard seed', 'saffron', 'fennel seed', 'tamarind', 'paneer tikka', 'chicken tikka', 'kadai paneer', 'rasgulla', 'kaju katli', 'barfi', 'ras malai', 'sandesh', 'mishti doi', 'bhakarwadi', 'kachori', 'malpua', 'chikki', 'kulcha', 'dhokla', 'poha', 'upma', 'sheera', 'medu vada', 'neer dosa', 'patra', 'pav bhaji', 'rabri', 'shrikhand', 'masala dosa', 'petha', 'murukku', 'mirchi bada', 'nimki', 'sabudana khichdi', 'khakhra', 'faafda', 'jaleba', 'balushahi', 'gujiya', 'mangalore bun', 'mysore pak', 'obi non', 'phirni', 'sukhdi', 'thepla', 'undhiyu' ],
    'Thai': [ 'thai', 'pad thai', 'green curry', 'red curry', 'yellow curry', 'massaman curry', 'panang curry', 'tom yum', 'tom kha gai', 'som tam', 'larb', 'laab', 'khao pad', 'pad krapow', 'pad see ew', 'sticky rice', 'mango sticky rice', 'thai basil chicken', 'papaya salad', 'satay', 'fish sauce', 'tamarind', 'coconut milk', 'lemongrass', 'galangal', 'kaffir lime leaves', 'thai chili', 'thai iced tea', 'thai beef salad', 'thai spring rolls', 'thai fish cakes', 'thai omelette', 'khao soi', 'thai fried rice', 'thai chicken soup', 'thai pork toast', 'thai hot pot', 'moo ping', 'gai yang', 'pla pao', 'nam tok', 'isaw', 'mookata', 'kanom jeen', 'thai boat noodles', 'chicken satay', 'pad pak', 'pad prik king', 'yam nua', 'thai pancake', 'khanom khrok', 'khao man gai', 'khao mu daeng', 'gaeng keow wan', 'gaeng som', 'pla muek pad prik', 'thai basil', 'mango with sticky rice', 'basil stir fry', 'nam prik', 'thai barbecue', 'thai curry', 'curry paste', 'thai desserts', 'thai soup', 'thai noodles', 'thai tea', 'thai coffee', 'banana fritters', 'coconut ice cream', 'thai rice', 'tapioca pudding', 'roti canai', 'pad pong karee', 'miang kham', 'som saa', 'yam pla duk fu', 'kaeng pa', 'kai jeow', 'ho mok pla', 'pad horapa', 'nam khao', 'thai crêpe', 'pla lard prik', 'thai papaya salad', 'thai beef jerky', 'thai stir fry', 'thai basil pork', 'thai seafood' ],
    'Spanish': [ 'spanish', 'paella', 'tapas', 'chorizo', 'gazpacho', 'tortilla española', 'churro', 'sangria', 'jamón ibérico', 'manchego', 'fabada', 'calamares', 'pulpo a la gallega', 'croquetas', 'pisto', 'ensaladilla rusa', 'patatas bravas', 'bocadillo', 'fideuà', 'gambas al ajillo', 'cocido', 'turrón', 'flan', 'crema catalana', 'montaditos', 'escabeche', 'sobrasada', 'alioli', 'albondigas', 'empanada', 'arroz negro', 'salmorejo', 'caracoles', 'merluza', 'bacalao', 'sidra', 'leche frita', 'chistorra', 'queso de cabra', 'aceitunas', 'pollo al ajillo', 'txipirones', 'boquerones', 'rabas', 'pan con tomate', 'anchoas', 'pimientos de padrón', 'txakoli', 'morcilla', 'butifarra', 'rosquillas', 'salpicón', 'zurrukutuna', 'gazpachuelo', 'pericana', 'ajo blanco', 'migas', 'arroz con leche', 'natillas', 'prawn', 'octopus', 'sardinas', 'pescado', 'carne', 'lentejas', 'mojama', 'caldereta', 'valdeón', 'tarta de Santiago', 'cordero', 'huevos rotos', 'revuelto', 'navajas', 'lomo', 'ortiguillas', 'marmitako', 'atún', 'cocochas', 'fuet', 'esqueixada', 'zarzuela', 'fritada', 'anguila', 'trucha', 'guiso', 'pote gallego', 'ropa vieja', 'caparrones', 'callos', 'bacalao a la vizcaina', 'rabas', 'regañas', 'bizcocho', 'mazapán', 'polvorones', 'chocolate con churros', 'orza', 'ensaimada', 'sobaos', 'pestiños', 'picadillo', 'zamburiñas' ],
    'Greek': [ 'greek', 'gyro', 'tzatziki', 'moussaka', 'souvlaki', 'feta', 'baklava', 'spanakopita', 'dolma', 'kleftiko', 'pastitsio', 'saganaki', 'horiatiki', 'taramasalata', 'keftedes', 'dolmades', 'tiropita', 'loukoumades', 'raki', 'ouzo', 'metaxa', 'hummus', 'baba ganoush', 'pita', 'avgolemono', 'bougatsa', 'galaktoboureko', 'meze', 'halloumi', 'hellenic', 'kalamata', 'tzatziki', 'gyros', 'falafel', 'spanakorizo', 'skordalia', 'melitzanosalata', 'kotopoulo', 'pasticcio', 'hortopita', 'kolokithokeftedes', 'fasolada', 'revithia', 'papoutsakia', 'gyro', 'koulouri', 'lagana', 'loukaniko', 'manouri', 'marides', 'masticha', 'melomakarona', 'myzithra', 'naxos', 'octopus', 'pasteli', 'retsinato', 'retsina', 'souzoukaklia', 'stifado', 'taramosalata', 'tiganites', 'vinsanto', 'xerotigana', 'yemista', 'yeros', 'halva', 'amygdalota', 'chortopita', 'ellinikos', 'kakavia', 'karydopita', 'kefalograviera', 'kourabiedes', 'kourkoubinia', 'ladopita', 'lahanodolmades', 'lakerda', 'makarounes', 'mavrodaphne', 'moustokouloura', 'mpaklava', 'ouzeri', 'pastourma', 'portokalopita', 'riganada', 'samali', 'sarikopitakia', 'soutzoukakia', 'spetsofai', 'spetsiotiko', 'spoon sweets', 'trahanas', 'tsoureki', 'vissino', 'vlita' ],
    'Mediterranean': [ 'mediterranean', 'hummus', 'falafel', 'tabbouleh', 'kebab', 'couscous', 'baba ganoush', 'feta', 'gyro', 'spanakopita', 'dolma', 'baklava', 'paella', 'souvlaki', 'moussaka', 'pesto', 'ratatouille', 'saganaki', 'taramasalata', 'tzatziki', 'halloumi', 'polenta', 'tapenade', 'aioli', 'briam', 'caprese', 'cioppino', 'fig', 'gazpacho', 'gratin', 'harissa', 'manchego', 'marzipan', 'panzanella', 'pecorino', 'prosciutto', 'risotto', 'saffron', 'salmorejo', 'sangria', 'tagine', 'tarator', 'borek', 'calamari', 'caponata', 'carpaccio', 'escabeche', 'farro', 'focaccia', 'gelato', 'gnocchi', 'grappa', 'gremolata', 'guanciale', 'limoncello', 'minestrone', 'ossobuco', 'panettone', 'pecorino', 'ribollita', 'saltimbocca', 'scampi', 'tiramisu', 'torta', 'truffle', 'umbricelli', 'vincotto', 'zabaglione' ],
    'Korean': [ 'korean', 'kimchi', 'bibimbap', 'bulgogi', 'galbi', 'japchae', 'tteokbokki', 'samgyeopsal', 'gimbap', 'banchan', 'gochujang', 'doenjang', 'samjang', 'sundubu jjigae', 'kimchi jjigae', 'galbitang', 'seolleongtang', 'mandu', 'pajeon', 'haemul pajeon', 'bossam', 'naengmyeon', 'jjajangmyeon', 'tteokguk', 'tteok', 'bingsu', 'soju', 'makgeolli', 'chimaek', 'hoddeok', 'gukbap', 'jangjorim', 'jang', 'jjigae', 'jokbal', 'juks', 'kongguksu', 'makkoli', 'mul naengmyeon', 'bibim naengmyeon', 'pojangmacha', 'soondae', 'tteok kkochi', 'yukgaejang', 'dakgalbi', 'hangover stew', 'hodduk', 'hotteok', 'jeon', 'kalguksu', 'kimbap', 'kongbiji jjigae', 'kongnamul', 'korean bbq', 'korean pancake', 'miyeokguk', 'muguk', 'naengchae', 'namul', 'ochazuke', 'patbingsu', 'patjuk', 'pyeongyang naengmyeon', 'sikhye', 'tteokgalbi', 'yangnyeom chicken', 'yukjeon', 'guk', 'hwajeon', 'japchae', 'jeotgal', 'jeukseok tteokbokki', 'jjamppong', 'jogaetang', 'jumeokbap', 'kalbijjim', 'kimchi bokkeumbap', 'kimchijeon', 'kkakdugi', 'kkochi', 'kongnamulguk', 'korean fried chicken', 'korean sushi', 'makchang gui', 'miyeok julgi bokkeum', 'myeolchi bokkeum', 'oisobagi', 'pa kimchi', 'saeutwigim', 'sigeumchi namul', 'songpyeon', 'sujebi', 'suyuk', 'woogeoji galbitang', 'yachaejeon', 'yeolmu kimchi', 'yeongeun jorim', 'yukhoe' ],
    'German': [ 'german', 'schnitzel', 'bratwurst', 'sauerkraut', 'pretzel', 'strudel', 'knödel', 'sauerbraten', 'spaetzle', 'rostbraten', 'leberkäse', 'bienenstich', 'schwarzwälder kirschtorte', 'pumpernickel', 'brötchen', 'wiener', 'schnellimbiss', 'kartoffelsalat', 'eintopf', 'rindsroulade', 'frikadellen', 'haxe', 'schweinshaxe', 'blutwurst', 'mettwurst', 'teewurst', 'weisswurst', 'currywurst', 'zigeunerschnitzel', 'kohlrouladen', 'maultaschen', 'brezel', 'pflaumenkuchen', 'kasespatzle', 'bretzel', 'stollen', 'quark', 'knoedel', 'gulasch', 'semmelknödel', 'kartoffelknödel', 'kartoffelpuffer', 'apfelstrudel', 'marzipan', 'leckuchen', 'weihnachtsstollen', 'speckkuchen', 'zwiebelkuchen', 'streuselkuchen', 'gerstensuppe', 'rehrücken', 'jaeger', 'kasseler', 'lebkuchen', 'obatzda', 'hasenpfeffer', 'himmel und erde', 'rollmops', 'saumagen', 'semla', 'schupfnudeln', 'serviettenknödel', 'tote oma', 'zimtstern', 'roggenbrot', 'weizenbrot', 'doppelbock', 'eisbein', 'flammkuchen', 'herrencreme', 'sülze', 'wurstsalat', 'bockwurst', 'frankfurter', 'königsberger klopse', 'laberkäse', 'nürnberger', 'rheinischer sauerbraten', 'senf', 'bratkartoffeln', 'donauwelle', 'hackbraten', 'käsekuchen', 'nudelsalat', 'sachertorte', 'thüringer', 'westfälischer schinken', 'berliner', 'krapfen', 'roter grütze', 'aachener printen', 'pfefferkuchen', 'spekulatius', 'windbeutel', 'baumkuchen', 'bismarckhering', 'buletten', 'fischbrötchen', 'gurkensalat', 'schmorkohl', 'zwiebelrostbraten', 'beerenauslese', 'eiswein', 'trockenbeerenauslese', 'glühwein' ],
    'Vietnamese': [ 'vietnamese', 'pho', 'banh mi', 'spring roll', 'goi cuon', 'bun cha', 'banh xeo', 'banh cuon', 'bun bo hue', 'goi', 'cha gio', 'nuoc cham', 'banh bao', 'ca phe sua da', 'banh khot', 'canh chua', 'chao', 'com tam', 'bun rieu', 'thit nuong', 'hu tieu', 'mi quang', 'banh canh', 'cao lau', 'bo luc lac', 'banh beo', 'banh trang', 'nem ran', 'goi ngo sen', 'ga nuong', 'bo bia', 'xoi', 'suon nuong', 'cha ca', 'banh bot loc', 'bun thit nuong', 'che', 'giai', 'tra da', 'cà phê trứng', 'mam tom', 'dua leo', 'rau muong', 'dau phu', 'trung chien', 'bun bo', 'banh tom', 'thit kho to', 'bi cuon', 'bun mang vit', 'bo kho', 'banh pate so', 'nem nuong', 'banh gio', 'bun dau mam tom', 'banh uot', 'banh chung', 'banh tet', 'banh day', 'cha lua', 'saigon', 'hoisin', 'fish sauce', 'lemongrass', 'tamarind', 'rice vinegar', 'galangal', 'rice paper' ],
    'Turkish': ['turkish', 'kebab', 'meze', 'baklava', 'lahmacun', 'kofte', 'dolma', 'börek', 'doner', 'pide', 'simits', 'çörek', 'manti', 'ayran', 'sucuk', 'ezogelin soup', 'muhammara', 'iskender', 'raki', 'menemen', 'gozleme', 'bulgur', 'şakşuka', 'acılı ezme', 'cacik', 'kumpir', 'lokma', 'tulumba', 'sarma', 'hummus', 'feta cheese', 'yogurt', 'halva', 'turkish delight', 'rose water', 'figs', 'dried apricots', 'pistachios', 'tea', 'turkish coffee', 'mercimek', 'köfte', 'biber', 'saray', 'galata', 'ottoman', 'anatolian', 'bursa', 'antep', 'adana', 'urfa', 'mediterranean', 'eggplant', 'black sea', 'tavuk', 'balık', 'mezze', 'kahvalti', 'olives', 'zeytin', 'peynir', 'pastırma', 'salep', 'sigara böreği', 'fistik', 'kadayif', 'şekerpare', 'yuvarlak', 'imam bayildi', 'karniyarik', 'hunkar begendi', 'pilav', 'çay', 'tarhana', 'gullac', 'ayva', 'kisir', 'lahana', 'maraş', 'midye', 'muhallebi', 'simit', 'tahini', 'tarama', 'trileçe', 'yaprak' ],
    'American': ['american', 'hamburger', 'hot dog', 'bbq', 'barbecue', 'grill', 'cornbread', 'macaroni and cheese', 'mac and cheese', 'baked beans', 'coleslaw', 'fried chicken', 'apple pie', 'pumpkin pie', 'cheesecake', 'buffalo wings', 'ranch dressing', 'meatloaf', 'potato salad', 'chili', 'jambalaya', 'gumbo', 'corn on the cob', 'clam chowder', 'pecan pie', 'key lime pie', 'sloppy joe', 'reuben sandwich', 'caesar salad', 'brisket', 'po’ boy', 'philly cheesesteak', 'new england clam chowder', 'texas toast', 'sourdough', 'cobb salad', 'biscuits and gravy', 'chicago deep dish pizza', 'new york pizza', 'detroit pizza', 'muffuletta', 'fajitas', 'nachos', 'peanut butter', 'jelly', 'jam', 's’mores', 'corn flakes', 'turkey', 'thanksgiving', 'smoked', 'biscuit', 'grits', 'hash browns', 'pancakes', 'waffles', 'maple syrup', 'milkshake', 'brownie', 'corn dog', 'beef jerky', 'lobster roll', 'pastrami', 'root beer', 'baked alaska', 'banana split', 'sundae', 'twinkie', 'cupcake', 'popcorn', 'buffalo dip', 'chowder', 'poached eggs', 'avocado toast', 'bagel', 'lox', 'chicken and waffles', 'surf and turf', 'pastrami on rye', 'pulled pork' ],
    'Brazilian': ['brazilian', 'feijoada', 'coxinha', 'pao de queijo', 'brigadeiro', 'caipirinha', 'acaraje', 'moqueca', 'farofa', 'churrasco', 'açaí', 'guarana', 'picanha', 'tutu de feijão', 'empada', 'pastel', 'cachaça', 'quindim', 'beiju', 'tapioca', 'carne seca', 'tucupi', 'cuscuz', 'mandioca', 'catupiry', 'carioca', 'paçoca', 'coconut water', 'pamonha', 'queijo coalho', 'cajuína', 'canjica', 'batida', 'bolo de rolo', 'caldo verde', 'aipim', 'acai bowl', 'capirinha', 'caldo de feijão', 'caju', 'carnaval', 'brazil nut', 'manioc', 'pastéis', 'vinaigrette', 'acarajé', 'pao de queijo', 'feijoada completa', 'samba', 'pao de queijo recipe', 'feijoada recipe', 'brigadeiros', 'pasteis', 'cachaça cocktail', 'coconut milk', 'cassava', 'brazilian beans', 'feijoada ingredients', 'brazilian desserts', 'brazilian side dishes', 'brazilian snacks', 'brazilian main dishes', 'brazilian drinks', 'brazilian street food', 'brazilian cuisine'],
    'Caribbean': ['caribbean', 'jerk', 'ackee', 'callaloo', 'plantain', 'roti', 'curry', 'rum', 'sorrel', 'coconut', 'conch', 'sancocho', 'guava', 'dumplings', 'breadfruit', 'cassava', 'barbecue', 'mango', 'tamarind', 'bammies', 'festival', 'chutney', 'pi...k', 'caribbean rice', 'saltfish', 'green banana', 'ackee and saltfish', 'coconut milk', 'bajan', 'grenadian', 'trinidadian', 'west indian', 'doubles', 'soursop', 'jamaican patties', 'curry goat', 'jamaican jerk', 'jamaican cuisine', 'caribbean food'],
    'Ethiopian': ['ethiopian', 'injera', 'doro wat', 'kitfo', 'tibs', 'berbere', 'shiro', 'mesir wat', 'tej', 'kocho', 'enset', 'niter kibbeh', 'gomen', 'atikilt wat', 'fitfit', 'kik alicha', 'dabo kolo', 'buna', 'beyaynetu', 'siga', 'ayib', 'tikel gomen', 'gored gored', 'chechebsa', 'genfo', 'awaze', 'timatim', 'firfir', 'tsom', 'mesob', 'talla', 'sambusa', 'tihlo', 'ambasha', 'kolo', 'awaze', 'etano', 'dabo', 'defo dabo', 'tebs', 'gebs', 'kulet', 'mies', 'bata', 'yemisir kik', 'yetsom', 'kulwa', 'korerima', 'koseret'],
    'Lebanese': ['lebanese', 'tabbouleh', 'hummus', 'falafel', 'shawarma', 'kebab', 'manakish', 'baklava', 'kibbeh', 'labneh', 'moussaka', 'zaatar', 'maqluba', 'fatayer', 'mloukhieh', 'sfiha', 'sambousek', 'fattoush', 'laban', 'tahini', 'mahshi', 'ras asfour', 'shanklish', 'kousa', 'batata', 'lahm bi ajeen', 'sujuk', 'baba ghanoush', 'warak enab', 'muhammara', 'samkeh harra', 'jibneh', 'lebanese bread', 'arayes', 'foul medames', 'kafta', 'lebanese salad', 'lebanese sweets', 'shawarma sandwich', 'halloumi'],
    'Moroccan': ['moroccan', 'couscous', 'tagine', 'harissa', 'pastilla', 'bastilla', 'mint tea', 'zaalouk', 'briouat', 'mechoui', 'rfissa', 'mrouzia', 'tanjiya', 'chermoula', 'kefta', 'maakouda', 'zalouk', 'bstilla', 'harcha', 'shebakia', 'msemen', 'rfissa', 'seffa', 'taktouka', 'meskouta', 'chakhchoukha', 'khobz', 'harira', 'makroud', 'zaalouk', 'besara', 'makfoul', 'sfouf', 'chicha', 'kalia', 'makrout', 'bradj', 'rghaif', 'zammita', 'shlada', 'kebab', 'tangia', 'ras el hanout', 'mlawi'],
    'Peruvian': ['peruvian', 'ceviche', 'lomo saltado', 'aji de gallina', 'anticuchos', 'papa a la huancaina', 'tiradito', 'causa', 'rocoto relleno', 'arroz con pollo', 'aji amarillo', 'seco de cordero', 'seco de res', 'chupe de camarones', 'cau cau', 'pisco sour', 'chicharron', 'jalea', 'tallarin saltado', 'ocopa', 'leche de tigre', 'picarones', 'sudado', 'cuy', 'rocoto', 'pachamanca', 'salsa criolla', 'carapulcra', 'adobo', 'empanadas peruanas', 'ensalada de quinoa', 'papa rellena', 'mazamorra morada', 'chifa', 'arroz chaufa', 'choclo', 'chicha morada', 'caigua', 'sancochado', 'tamal', 'caigua rellena', 'leche asada', 'tacu tacu', 'aji panca', 'caldo de gallina', 'alfajores'],
    'Russian': ['russian', 'borscht', 'pelmeni', 'blini', 'beef stroganoff', 'caviar', 'solyanka', 'pirozhki', 'shchi', 'kvass', 'kasha', 'golubtsy', 'kholodets', 'okroshka', 'vinegret', 'syrniki', 'olivier salad', 'sbiten', 'zakuski', 'vodka', 'pirogi', 'piroshki', 'sour cream', 'kvass', 'smetana', 'rye bread', 'medovik', 'napoleon cake', 'shashlik', 'pirozhki', 'ptichye moloko', 'rye bread', 'syrniki', 'ukha', 'kompot', 'schi', 'shashlyk', 'plov', 'blintzes', 'kvas', 'pelmeny', 'rassolnik', 'sbiten', 'medovukha', 'shuba salad', 'vareniki', 'kvass'],
    'Scandinavian': ['scandinavian', 'smorgasbord', 'gravlax', 'herring', 'pickled herring', 'cured salmon', 'sild', 'potato salad', 'koldtbord', 'meatballs', 'lingonberry', 'rösti', 'rhubarb', 'cabbage rolls', 'jansson’s temptation', 'princess cake', 'glögg', 'aquavit', 'kräftskiva', 'kladdkaka', 'sill', 'sursild', 'rye bread', 'kringel', 'lussekatter', 'kanelbullar', 'open-faced sandwiches', 'karelian pasties', 'cinnamon rolls', 'smørrebrød', 'rødgrød', 'kjøttkaker', 'lapskaus', 'fårikål', 'kjøttboller', 'lutefisk', 'rakfisk', 'surströmming', 'hakarl', 'rågbröd', 'prinsesstårta', 'schnapps', 'herb cheese', 'karjalanpiirakka', 'karjalanpaisti', 'ryebread'],
    'South African': ['south african', 'bobotie', 'biltong', 'boerewors', 'braai', 'chakalaka', 'bunny chow', 'malva pudding', 'sosatie', 'koeksister', 'biltong', 'vetkoek', 'bobotie', 'potjiekos', 'melktert', 'amekicane', 'chutney', 'biltong', 'boerewors', 'bunny chow', 'denningvleis', 'droewors', 'kaiings', 'koeksisters', 'mealie bread', 'milktart', 'rusks', 'skilpadjies', 'sosaties', 'umngqusho'],
    'Australian': ['australian', 'damper', 'pavlova', 'anzac biscuits', 'lamingtons', 'meat pie', 'sausage roll', 'chiko roll', 'tim tam', 'fairy bread', 'barramundi', 'kangaroo', 'emu', 'crocodile', 'Vegemite', 'pumpkin scone', 'Aussie burger', 'bush tucker', 'bush tomato', 'macadamia nuts', 'emu eggs', 'wattleseed', 'lemon myrtle', 'bush banana', 'finger lime', 'warrigal greens', 'bunya nut', 'lilli pilli', 'quandong', 'bush plum', 'yabby', 'witchetty grub', 'Wallaby', 'Crocodile', 'John Dory'],
    'Cuban': ['cuban', 'ropa vieja', 'mojito', 'cuban sandwich', 'medianoche', 'lechon asado', 'tostones', 'moros y cristianos', 'croquetas', 'empanadas', 'picadillo', 'yuca con mojo', 'pastelitos', 'arroz con pollo', 'pan con bistec', 'flan', 'guava pastelitos', 'malanga fritters', 'cuban black beans', 'cuban coffee', 'guava', 'plantains', 'tostada', 'yucca', 'taro', 'yautia', 'malanga', 'batata', 'calabaza', 'papaya', 'mamey', 'guanabana', 'sugar cane'],
    'Filipino': ['filipino', 'adobo', 'sinigang', 'kare-kare', 'lechon', 'pancit', 'sisig', 'turon', 'halo-halo', 'balut', 'bibingka', 'pandesal', 'lumpia', 'tapa', 'longganisa', 'ensaymada', 'caldereta', 'tinola', 'pinakbet', 'bicol express', 'bulalo', 'dinuguan', 'batchoy', 'leche flan', 'ube', 'mango float', 'champorado', 'pancit molo', 'siopao', 'siomai', 'pan de coco', 'cassava cake', 'puto', 'kinilaw', 'buko pie', 'taho', 'tapsilog', 'bangus', 'taho', 'buko'],
    'Indonesian': ['indonesian', 'nasi goreng', 'rendang', 'sate', 'gado-gado', 'nasi padang', 'bakso', 'soto', 'ayam goreng', 'nasi kuning', 'mie goreng', 'ikan bakar', 'perkedel', 'sambal', 'pecel', 'martabak', 'babi guling', 'lumpia', 'bubur ayam', 'ayam bakar', 'gado gado', 'bubur', 'tahu', 'tempeh', 'krupuk', 'serundeng', 'peyek', 'lemper', 'pempek', 'ikan', 'kerupuk', 'nasi', 'sambal', 'rempah', 'ayam', 'ikan', 'daging', 'telur', 'sate', 'tempe'],
    'Malaysian': ['malaysian', 'nasi lemak', 'rendang', 'satay', 'roti canai', 'mee goreng', 'nasi goreng', 'laksa', 'hainanese chicken rice', 'char kway teow', 'nasi kerabu', 'murtabak', 'rojak', 'curry laksa', 'mee rebus', 'nasikandar', 'cendol', 'kuih', 'ais kacang', 'otak-otak', 'apam balik', 'nasi ayam', 'nasi kukus', 'nasi dagang', 'sambal belacan', 'satay celup', 'kaya toast', 'teh tarik', 'nasi ulam', 'nasi minyak', 'pisang goreng', 'sup kambing', 'kari', 'ikan bakar', 'sambal', 'rendang', 'laksa', 'rojak'],
    'Cajun/Creole (Louisiana, USA)': ['cajun', 'creole', 'gumbo', 'jambalaya', 'crawfish', 'etouffee', 'po-boy', 'andouille', 'red beans and rice', 'beignets', 'muffuletta', 'boudin', 'blackened fish', 'alligator', 'shrimp étouffée', 'dirty rice', 'turducken', 'king cake', 'maque choux', 'crawfish boil', 'gator tail', 'gumbo', 'crab boil', 'redfish courtbouillon', 'jambalaya', 'mirliton', 'oyster po-boy', 'shrimp and grits', 'turkey and sausage gumbo', 'catfish courtbouillon', 'boudin balls', 'turtle soup', 'remoulade sauce'],


}

"""# **Count Mentions**"""

def count_cuisine_mentions(df, cuisine_keywords):
    cuisine_counts = {cuisine: 0 for cuisine in cuisine_keywords}
    for cuisine, keywords in cuisine_keywords.items():
        for keyword in keywords:
            cuisine_counts[cuisine] += df['name'].str.contains(keyword, case=False, na=False).sum()
            cuisine_counts[cuisine] += df['description'].str.contains(keyword, case=False, na=False).sum()
    return cuisine_counts

cuisine_mentions = count_cuisine_mentions(names, cuisine_keywords)

# Sort the cuisine_mentions dictionary by keys in ascending order
sorted_cuisine_mentions = {k: v for k, v in sorted(cuisine_mentions.items(), key=lambda item: item[0])}

# Display the results
for cuisine, mentions in sorted_cuisine_mentions.items():
    print(f"{cuisine}: {mentions} mentions")

"""# **Function to Your DataFrame**"""

cuisine_mentions = count_cuisine_mentions(names, cuisine_keywords)
print(cuisine_mentions)

"""# **Chart of Bias**"""

def count_cuisine_mentions(df, cuisine_keywords):
    cuisine_counts = {cuisine: 0 for cuisine in cuisine_keywords}
    for cuisine, keywords in cuisine_keywords.items():
        for keyword in keywords:
            cuisine_counts[cuisine] += df['name'].str.contains(keyword, case=False, na=False).sum()
            cuisine_counts[cuisine] += df['description'].str.contains(keyword, case=False, na=False).sum()
    return cuisine_counts

cuisine_mentions = count_cuisine_mentions(names, cuisine_keywords)

# Sort the cuisine_mentions dictionary by values in descending order
sorted_cuisine_mentions = {k: v for k, v in sorted(cuisine_mentions.items(), key=lambda item: item[1], reverse=True)}

# Extract cuisine names and mentions counts
cuisines = list(sorted_cuisine_mentions.keys())
mentions = list(sorted_cuisine_mentions.values())

# Plot the bar chart
plt.figure(figsize=(10, 6))
plt.barh(cuisines, mentions, color='skyblue')
plt.xlabel('Mentions')
plt.ylabel('Cuisine')
plt.title('Bias of Food Mentions')
plt.gca().invert_yaxis()  # Invert y-axis to display cuisine with highest mentions at the top
plt.show()